name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set tag
        id: vars
        run: echo "sha_short=$(echo ${GITHUB_SHA::7})" >> $GITHUB_OUTPUT
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/timeoff:${{ steps.vars.outputs.sha_short }}
  CD:
    runs-on: ubuntu-latest
    steps:
      - 
        name: update k8s manifest in infra repo
        run: |
          export INFRA_REPO=https://${{secrets.GH_TOKEN}}@github.com/damiango/timeoff-management-infra.git
          export MANIFEST_PATH=k8s/
          export RELEASE_VERSION=${{ steps.vars.outputs.sha_short }}
          
          git clone $MANIFEST_REPO

          cd $MANIFEST_PATH

          sed -i '/image:/ s/timeoff:.*/timeoff:$RELEASE_VERSION/g' timeoff-app.yaml

          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Version $RELEASE_VERSION"
            git push
            echo "Updated manifest to version $RELEASE_VERSION";
          else
            echo "Error: The manifest is already updated to the version $RELEASE_VERSION";
            exit 1
          fi